version: 0.1
phases:
  install:
    commands:
      - npm install serverless --silent --no-progress -g
  pre_build:
    commands:
      - npm install --silent --no-progress
  build:
    commands:
      - serverless dynamodb install
      # - yarn test
  post_build:
    commands:
      - serverless deploy --stage prod

artifacts:
  files:
    - serverless.yml
