version: 0.1
phases:
  install:
    commands:
      - npm install --silent --no-progress -g yarn
      - yarn global add serverless --silent --no-progress
  pre_build:
    commands:
      - yarn install --silent --no-progress
      - serverless dynamodb install >/dev/null
  build:
    commands:
      - yarn test
      - mkdir -p target/stage
      - mkdir target/prod
      - serverless package --package target/stage --stage stage -v -r us-east-1
      - serverless package --package target/prod --stage prod -v -r us-east-1
  post_build:
    commands:
      # - serverless deploy --stage prod

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
