version: 0.1
phases:
  install:
    commands:
      - npm install --silent --no-progress -g yarn
      - yarn global add serverless --silent --no-progress
  pre_build:
    commands:
      - yarn install --silent --no-progress
      - serverless dynamodb install >/dev/null
  build:
    commands:
      - yarn test

artifacts:
  files:
    - serverless.yml
